version: '3.1'
services:
  stats-server:
    image: amazoncorretto:11
    container_name: ewm-stats-service
    ports:
      - "9090:9090"
    depends_on:
        - stats-db
    volumes:
        - ./ewm-stats/stats-server/target/stats-server-0.0.1-SNAPSHOT.jar:/stats-service-app.jar
    entrypoint: ["java","-jar","/stats-service-app.jar"]
    environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm_stats
        - SPRING_DATASOURCE_USERNAME=ewm
        - SPRING_DATASOURCE_PASSWORD=ewm

  stats-db:
    image: postgres:14-alpine
    container_name: ewm-stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewm_stats
      - POSTGRES_USER=ewm
      - POSTGRES_PASSWORD=ewm

  ewm-service:
    image: amazoncorretto:11
    container_name: ewm-main-service
    ports:
      - "8080:8080"
    depends_on:
        - ewm-db
    volumes:
        - ./ewm-main-service/target/ewm-main-service-0.0.1-SNAPSHOT.jar:/main-service-app.jar
    entrypoint: ["java","-jar","/main-service-app.jar"]
    environment:
        - EWM_STATS_SERVER_URL=http://stats-server:9090
        - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm_main
        - SPRING_DATASOURCE_USERNAME=ewm
        - SPRING_DATASOURCE_PASSWORD=ewm

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-main-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewm_main
      - POSTGRES_USER=ewm
      - POSTGRES_PASSWORD=ewm
